# Generated by Django 2.1.1 on 2018-10-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0056_auto_20180908_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalOneWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(choices=[('VMC Basic', 'VMC Basic'), ('Herman Basic', 'Herman Basic'), ('Fatima001', 'Fatima001'), ('OLISCC', 'OLISCC'), ('KINSCC', 'KINSCC'), ('VICSCC', 'VICSCC'), ('MCDSCC', 'MCDSCC')], default='', max_length=30)),
                ('service_type', models.CharField(choices=[('VMC Wheelchair', 'VMC Wheelchair'), ('VMC Ambulatory', 'VMC Ambulatory'), ('VMC Discharge', 'VMC Discharge'), ('VMC Bariatric', 'VMC Bariatric'), ('HERMAN Wheelchair', 'HERMAN Wheelchair'), ('HERMAN Ambulatory', 'HERMAN Ambulatory'), ('HERMAN Bariatric', 'HERMAN Bariatric')], default='', max_length=15)),
                ('patient_first_name', models.CharField(default='', max_length=50)),
                ('patient_last_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('patient_phone', models.CharField(max_length=10)),
                ('patient_birthdate', models.CharField(max_length=8)),
                ('number_of_passengers', models.PositiveIntegerField(default=1)),
                ('appointment_date', models.CharField(max_length=15)),
                ('round_trip', models.BooleanField(default=False)),
                ('pickup_time', models.CharField(max_length=10)),
                ('return_time', models.CharField(blank=True, max_length=10, null=True)),
                ('pickup_address', models.CharField(max_length=200)),
                ('destination_address', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded', models.BooleanField(default=False)),
                ('dl_user', models.CharField(default='', max_length=200)),
                ('dl_time', models.CharField(default='', max_length=200)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
