# Generated by Django 2.1.1 on 2018-09-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date_time', models.CharField(max_length=100)),
                ('end_date_time', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
