# Generated by Django 2.1.1 on 2018-09-20 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reocurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(default='', max_length=100)),
                ('service_type', models.CharField(default='', max_length=100)),
                ('call_number', models.CharField(default='', max_length=100)),
                ('diag_code', models.CharField(default='', max_length=100)),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=10)),
                ('bday', models.CharField(default='', max_length=100)),
                ('med_num', models.CharField(default='', max_length=100)),
                ('num_pass', models.PositiveIntegerField(max_length=1)),
                ('start_add', models.CharField(default='', max_length=100)),
                ('end_add', models.CharField(default='', max_length=100)),
                ('start_time', models.CharField(default='', max_length=100)),
                ('end_time', models.CharField(default='', max_length=100)),
                ('start_date', models.CharField(default='', max_length=100)),
                ('end_date', models.CharField(default='', max_length=100)),
                ('weekdays', models.CharField(default='', max_length=100)),
                ('roundtrip', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
