# Generated by Django 2.1.1 on 2018-09-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reocurring',
            name='num_pass',
            field=models.PositiveIntegerField(),
        ),
    ]
